services:
    bot:
                container_name: buddy-backend-bot
                restart: unless-stopped
                build:
                    context: .
                    dockerfile: Dockerfile
                environment:
                    - NODE_ENV=production
    postgres:
                container_name: buddy-backend-postgres
                image: postgres:latest
                restart: unless-stopped
                environment:
                    - POSTGRES_USER=buddy-backend
                    - POSTGRES_PASSWORD=dbd9087915ef9dfbf2c61fe5
                    - POSTGRES_DB=buddy-backend
                volumes:
                    - postgres_data:/var/lib/postgresql/data
    redis:
                container_name: buddy-backend-redis
                image: redis:latest
                command: [ "redis-server", "--maxmemory-policy", "noeviction" ]
                restart: unless-stopped
                volumes:
                    - redis_data:/data
volumes:
    postgres_data:
    redis_data:
    
networks:
    default: {}